sudo: false
language: python
python:
  - "3.7"

matrix:
  include:
  - os: linux
    python: "3.7"
  - os: osx
    python: "3.7"
  - os: windows
    python: "3.7"

install:
  - pip install six blist unittest2 pytz
  - pip install -e .
script: python tests/tests.py
